# Generated by Django 4.2.7 on 2023-11-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('message', models.TextField()),
                ('when_add', models.DateTimeField(auto_now_add=True)),
                ('road', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
