# Generated by Django 4.2.7 on 2023-11-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_app', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
